config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home", as: 'home'

  root to: 'pages#landing'
  get '/home', to: 'pages#home', as: 'home'
  get 'list', to: 'pages#list', as: 'list'
  get 'list_2', to: 'pages#list_2', as: 'list_2'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :incidents
  resources :incidents, only: [:show] do
    resources :chatrooms, only: [:create, :index]
  end
  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  has_one_attached :photo
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :user
  belongs_to :user_two, class_name: 'User'
  belongs_to :incident
  has_one_attached :photo
end

app/models/incident.rb
class Incident < ApplicationRecord
  belongs_to :user
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  TYPES = ["Roubo", "Furto", "Assédio", "Outros"]

  validates :location, presence: true
  validates :description, presence: true
  validates :incident_type, presence: true, inclusion: { in: TYPES }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chatrooms
  has_one_attached :photo
  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit::Authorization
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
after_action :skip_authorization

  def show
    # authorize @chatroom
    @chatroom = Chatroom.find(params[:id])
    @incident = @chatroom.incident
    @chatroom.user.avatar = "boy.png"
    @chatroom.user_two.avatar = "avatar.png"
    @message = Message.new
    @chatrooms_all = policy_scope(Chatroom)
    @chatrooms = Chatroom.where(user: current_user).or(Chatroom.where(user_two: current_user))
  end

  def create
    @incident = Incident.find(params[:incident_id])
    @user = @incident.user
    @user.avatar = "boy.png"
    @user_two = current_user
    @user_two.avatar = "avatar.png"
    @chatroom = Chatroom.create(user: @user, user_two: @user_two, name: "#{@user.nickname}-#{@user_two.nickname}", incident: @incident)
    redirect_to chatroom_path(@chatroom)
  end

  def index
    @incident = Incident.find(params[:incident_id])
    @user = @incident.user
    @chatrooms_all = policy_scope(Chatroom)
    @chatrooms = @chatrooms_all.where(user: @user)
  end
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: %i[show edit update destroy]

  def show
    authorize @incident
    if @incident.incident_type == "Roubo"
      link_url = "https://res.cloudinary.com/deofzbzjp/image/upload/v1669836325/PIN_ROUBO-removebg-preview_ltnpyp.png"
    elsif @incident.incident_type == "Furto"
      link_url = "https://res.cloudinary.com/deofzbzjp/image/upload/v1669836325/PIN_FURTO-removebg-preview_jmgj8x.png"
    elsif @incident.incident_type == "Assédio"
      link_url = "https://res.cloudinary.com/deofzbzjp/image/upload/v1669926859/PIN_ASS%C3%89DIO_w3nz5l.png"
    else
      link_url = "https://res.cloudinary.com/deofzbzjp/image/upload/v1669836325/PIN_OUTROS-removebg-preview_sisizq.png"
    end

    @markers = [
      {
        lat: @incident.latitude,
        lng: @incident.longitude,
        info_window: render_to_string(partial: "pages/info_window", locals: {incident: @incident}),
        image_url: helpers.asset_url(link_url)
      }
    ]

    @marker =
      {
        lat: @incident.latitude,
        lng: @incident.longitude,
        info_window: render_to_string(partial: "pages/info_window", locals: {incident: @incident}),
        image_url: helpers.asset_url(link_url)
      }
  end

  def new
    @incident = Incident.new
    authorize @incident
  end

  def create
    @incident = Incident.new(incident_params)
    @incident.user = current_user
    authorize @incident
    if @incident.save
      redirect_to incident_path(@incident)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @incident
  end

  def update
    authorize @incident
    if @incident.update(incident_params)
      redirect_to @incident, notice: "Incidente editado com sucesso!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @incident
    @incident.destroy
    redirect_to home_path, status: :see_other
  end

  private

  def set_incident
    @incident = Incident.find(params[:id])
  end

  def incident_params
    params.require(:incident).permit(:incident_type, :location, :description, :photo)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  after_action :skip_authorization

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: {message: @message})
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:landing]

  def home
    @incidents = Incident.all
    # The `geocoded` scope filters only incidents with coordinates
    @markers = @incidents.geocoded.map do |incident|
      if incident.incident_type == "Roubo"
        link_url = "https://res.cloudinary.com/deofzbzjp/image/upload/v1669836325/PIN_ROUBO-removebg-preview_ltnpyp.png"
      elsif incident.incident_type == "Furto"
        link_url = "https://res.cloudinary.com/deofzbzjp/image/upload/v1669836325/PIN_FURTO-removebg-preview_jmgj8x.png"
      elsif incident.incident_type == "Assédio"
        link_url = "https://res.cloudinary.com/deofzbzjp/image/upload/v1669926859/PIN_ASS%C3%89DIO_w3nz5l.png"
      elsif incident.incident_type == "polícia"
        link_url = "https://res.cloudinary.com/dwvglguvp/image/upload/v1670244032/development/vigilante/PIN_VIgilante-removebg-preview_cdthq2.png"
      else
        link_url = "https://res.cloudinary.com/deofzbzjp/image/upload/v1669836325/PIN_OUTROS-removebg-preview_sisizq.png"
      end
      {
        lat: incident.latitude,
        lng: incident.longitude,

        info_window: render_to_string(
          partial: "info_window",
          locals: {incident: incident}
        ),
        image_url: helpers.asset_url(link_url)

      }
    end
  end

  def landing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/index.html.erb
<% @chatrooms.each do |chat| %>
  <p><%= link_to chat.name, chatroom_path(chat) %></p>
<% end %>

app/views/chatrooms/show.html.erb
<div class="container chat-grid">
  <div class="chatrooms">
    <h2>Chatrooms</h2>
    <ul class="list-group">
      <% @chatrooms.each do |chat| %>
        <% if chat.user.photo.attached? %>
          <li><%= cl_image_tag chat.user.photo.key, class: "avatar-chat" %> <%= link_to chat.name, chatroom_path(chat) %></li>
        <% else %>
          <li><%= image_tag "avatar.png", class: "avatar-chat" %> <%= link_to chat.name, chatroom_path(chat) %></li>
        <% end %>
      <% end %>
    </ul>
  </div>

  <div class="container chatroom justify-content-center"
    data-controller="chatroom-subscription"
    data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">

    <div class="d-flex align-items-center">
      <h1>#<%= @chatroom.name %></h1>
    </div>

    <div class="messages" data-chatroom-subscription-target="messages">
      <% @chatroom.messages.each do |message| %>
        <%= render "messages/message", message: message, incident: @incident %>
      <% end %>
    </div>

    <%= simple_form_for [@chatroom, @message],
    html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
    %>
      <%= f.input :content,
        label: false,
        placeholder: "Message ##{@chatroom.name}",
        wrapper_html: {style: "margin-bottom: 0px !important; width: 100%;"}
      %>
      <%= f.submit "Enviar", class: "btn mb-3" %>
    <% end %>
  </div>
</div>

app/views/incidents/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <div class= "incident-form text-center">
      <img src="https://cdn-icons-png.flaticon.com/512/2797/2797388.png" alt="alert" width="50" height="50">
      <h3>Relatar um incidente</h2>
        <%= simple_form_for(@incident) do |f| %>
        <div class="form-group">
          <%= f.input :incident_type,  label: 'Tipo de incidente', class: "form-control dropdown", collection: Incident::TYPES %>
          <%= f.input :location,
            label: 'Localização',
            input_html: {data: {address_autocomplete_target: "location"}, class: 'd-none m-0'},
            wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
          %>
          <%= f.input :description, label: 'Descrição' %>
          <%= f.button :submit, "Relatar incidente", class: "btn" %>
        <% end %>
    </div>
  </div>
</div>

app/views/incidents/edit.html.erb
<%= render "form", incident: @incident %>

app/views/incidents/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <div class= "incident-form text-center">
      <img src="https://cdn-icons-png.flaticon.com/512/2797/2797388.png" alt="alert" width="50" height="50">
      <h3>Relatar um incidente</h2>
        <%= simple_form_for(@incident) do |f| %>
        <div class="form-group">
          <%= f.input :incident_type, label: 'Tipo de incidente', class: "form-control dropdown", collection: Incident::TYPES %>
          <%= f.input :location, label: 'Endereço' %>
          <%= f.input :description, label: 'Descrição' %>
          <%= f.button :submit, "Relatar incidente", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/incidents/show.html.erb
<% if @incident.location.present? %>
  <div class="d-flex justify-content-between text-center w-100">
    <div class="row w-100 align-items-center bg-white ps-3">
      <div class="col-sm-12 col-md-6 mt-2">
          <h4> <strong> <%= @incident.incident_type %> </strong></h4>
          <p class="mb-5"> Incidentes na região: <%= @incident.geocoded? ? @incident.nearbys(2).count(:all) : 0  %> </p>

        <div class="mt-5 mb-4">
          <%= image_tag "https://res.cloudinary.com/dwvglguvp/image/upload/c_crop,w_798/v1669987359/development/vigilante/1000_F_518511462_iNQzBBvxZNVwTw9DRyVyjh5X27HPJbJ2_rfdkih.jpg",
          style:"width:150px; height:150px;"%>
        </div>
        <p> <i class="fa-solid fa-location-dot"></i> <%= @incident.location %></p>
        <p><strong>Descrição: </strong><%= @incident.description%></p>
        <% if policy(@incident).edit? %>
          <%= link_to "Editar", edit_incident_path(@incident), class: 'btn btn-outline-secondary rounded-pill mt-3' %>

        <% end %>
        <% if policy(@incident).destroy? %>
          <%= link_to "Deletar", incident_path(@incident), data: {turbo_method: :delete, turbo_confirm: "Tem certeza?"}, class: 'btn btn-outline-secondary rounded-pill mt-3'%>
        <% end %>
        <% unless @incident.user == current_user %>
          <% chat = Chatroom.find_by(incident: @incident, user_two: current_user) %>
          <% if chat.present? %>
            <%= link_to "Chat", chatroom_path(chat), class: 'btn btn-outline-secondary rounded-pill mt-3' %>
          <% else %>
            <%= link_to "Chat", incident_chatrooms_path(@incident), data: {turbo_method: :post}, class: 'btn btn-outline-secondary rounded-pill mt-3' %>
          <% end %>
        <% end %>
    </div>
      <div class="col-6">
        <div style="width: 103.7%"
          class="map-container"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-marker-value="<%= @marker.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
<%else%>
  <div class="d-flex justify-content-between text-center w-100">
    <h2 class="text-center"> Desculpe, esse endereço não existe 😿 </h2>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vigilante</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <style>
      <% if current_user %>
      <%= ".message-chat.message-user-#{current_user.id}" %>  {
        background-color: white;
        color: black;
        flex-direction: row;
      }
       <%= ".message-chat.message-user-#{current_user.id} .gap-chat" %>  {
        text-align: end;
        justify-content: flex-end;
        align-items: flex-end;
      }
      <% end %>
    </style>
  </head>

  <body>
  <% unless action_name == "landing" %>
    <%= render "shared/navbar" %>
  <% end %>
  <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <div class="message-chat message-user-<%= message.user.id %>">
    <%#= image_tag url_for(message.user.photo), class: "avatar-chat" %>

    <div class="d-flex w-100 gap-chat flex-column">
      <small class="container-white">
        <% if message.user.photo.attached? %>
          <%= cl_image_tag message.user.photo.key, class: "avatar-chat" %>
        <% else %>
          <%= image_tag ("avatar.png"), class: "avatar-chat"  %>
        <% end %>
        <strong><%= message.user.nickname %></strong>
        <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
      </small>
      <p><%= message.content %></p>
    </div>
  </div>
</div>

app/views/pages/_info_window.html.erb
<h6><%= link_to incident.incident_type, incident_path(incident), class: 'text-dark' %></h6>
<hr>
<p><%= incident.location %></p>

app/views/pages/home.html.erb
<div class="map-container"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/pages/landing.html.erb
<%= link_to "/home" do %>
<div class="landing-page vw-100" style="background-image: url(https://res.cloudinary.com/dwvglguvp/image/upload/v1670260212/development/vigilante/vigilante_1_vhg2py.png);">
</div>
<% end %>

app/views/pages/list.html.erb
<div class="list">
  <main>
    <div class="container-title">
      <h3>Bairros com mais incidentes:</h3>
    </div>

    <div class="container ">
      <ol class="danger-list">
        <li> Campo Limpo: <%= Incident.near([-23.632947704703927, -46.7555051841067],5).count(:all) %> incidentes </li>
        <li> Capão Redondo: <%= Incident.near([-23.662935, -46.766866],5).count(:all) %> incidentes </li>
        <li> Taboão: <%= Incident.near([-23.669117, -46.606639],5).count(:all) %> incidentes </li>
        <li> Santana: <%= Incident.near([-23.489438, -46.626297],5).count(:all) %> incidentes </li>
        <li> Guaianases: <%= Incident.near([-23.555267, -46.412053],5).count(:all) %> incidentes </li>
      </ol>
    </div>
  </main>
</div>

app/views/pages/list_2.html.erb
<div class="list">
  <main>
    <div class="container-title">
      <h3>Bairros com menos incidentes: </h3>
    </div>

    <div class="container ">
      <ol class="danger-list-2">
        <li> Vila Nova Conceição: 0 Incidentes</li>
        <li> Itaim Bibi: 1 Incidente</li>
        <li> Moema: 2 Incidentes</li>
        <li> Jardins: 3 Incidentes</li>
        <li> Perdizes: 5 Incidentes</li>
      </ol>
    </div>
  </main>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <div class="container-fluid text-light row--vertical-center">
    <%= link_to home_path, class: "navbar-brand" do %>
      <%= "VIG!LANTE" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to new_incident_path, class: "nav-link text-white" do %>
              <%= "Relatar incidente" %>
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to "https://www.delegaciaeletronica.policiacivil.sp.gov.br/ssp-de-cidadao/pages/comunicar-ocorrencia",target: '_blank', class: "nav-link text-white" do %>
              <%= "Comunicar B.O" %>
            <% end %>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false", aria-haspopup= "true">
              Ranking bairros
            </a>
            <ul class="dropdown-menu dropdown-menu-light">
              <li><%= link_to "Mais incidentes", list_path, class: "dropdown-item" %></li>
              <li><%= link_to "Menos incidentes", '/list_2', class: "dropdown-item" %></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <%if current_user && current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, :width=>50, :height=>50, :gravity=>"face", :crop=>"fill", class:"avatar dropdown-toggle", id:"navbarDropdown", "type" => "button", "data-bs-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%elsif current_user && !current_user.photo.attached?%>
                <%=image_tag "https://res.cloudinary.com/dwvglguvp/image/upload/v1669923543/development/vigilante/avatar_c4ytkf.png", :width=>25, :height=>25, :gravity=>"face", :crop=>"fill", class:"avatar dropdown-toggle", id:"navbarDropdown", "type" => "button", "data-bs-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false"%>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% end %>
              <p class="text-center mt-2"> <%= current_user.nickname %> </p>

              <hr>

                <p class="dropdown-item">
                  <% chat = Chatroom.where(user: current_user).or(Chatroom.where(user_two: current_user)) %>
                    <% if chat.present? %>
                      <%= link_to "Chatrooms", chatroom_path(chat[0]), class: 'text-decoration-none text-dark' %>
                    <% end %>
                </p>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
          </li>

        <% else %>
          <li class="nav-item" >
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>